# Generated by Django 3.2.20 on 2023-08-08 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='../default_post_chzmzw.jpg', upload_to='images/')),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('food', 'Food'), ('fashion', 'Fashion'), ('nature', 'Nature'), ('art', 'Art'), ('music', 'Music'), ('sports', 'Sports'), ('technology', 'Technology'), ('books', 'Books'), ('health', 'Health'), ('fitness', 'Fitness'), ('movies', 'Movies'), ('gaming', 'Gaming'), ('crafts', 'Crafts'), ('cars', 'Cars'), ('pets', 'Pets'), ('animals', 'Animals'), ('home', 'Home'), ('education', 'Education'), ('outdoors', 'Outdoors'), ('photography', 'Photography'), ('others', 'Others')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
