# Generated by Django 3.2.20 on 2023-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel'), ('food', 'Food'), ('fashion', 'Fashion'), ('nature', 'Nature'), ('art', 'Art'), ('music', 'Music'), ('sports', 'Sports'), ('technology', 'Technology'), ('books', 'Books'), ('health', 'Health'), ('fitness', 'Fitness'), ('movies', 'Movies'), ('gaming', 'Gaming'), ('crafts', 'Crafts'), ('cars', 'Cars'), ('pets', 'Pets'), ('animals', 'Animals'), ('home', 'Home'), ('education', 'Education'), ('outdoors', 'Outdoors'), ('photography', 'Photography'), ('others', 'Others')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_chzmzw.jpg', upload_to='images/'),
        ),
    ]
